name: Docker Image CI

on:
  workflow_dispatch:
  release: 
    types: [created]
    branches: [main, master]
    tags: v**
    

jobs:

  maven_package:
    uses: ./.github/workflows/maven-package-template.yml

  display_app_version:
    runs-on: ubuntu-latest
    needs: maven_package
    steps:
      - run: echo ${{ needs.maven_package.outputs.app_version }}
      
  docker_image:
    uses: ./.github/workflows/docker-test-image-template.yml
    needs: maven_package
