name: Docker Image CI

on:
  workflow_dispatch:
  release: 
    types: [created]
    branches: [main, master]
    tags: v**
    

jobs:

  maven_package:
    uses: ./.github/workflows/maven-package-template.yml
    
  display_app_version:
    runs-on: ubuntu-latest
    needs: maven_package
    steps:
      - run: echo ${{ needs.maven_package.outputs.app_version }}
      
  sonar:
    uses: ./.github/workflows/sonarcloud.yml
    permissions:
      pull-requests: read
    secrets: inherit
    needs: maven_package

      
  docker_image:
    permissions:
      contents: read
      packages: write
    secrets: inherit
    uses: ./.github/workflows/docker-test-image-template.yml
    needs: 
      - maven_package
      - display_app_version

