name: Java Maven Package

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, reopened]

jobs:
  maven_package:
    uses: ./.github/workflows/maven-package-template.yml

  display_app_version:
    runs-on: ubuntu-latest
    needs: maven_package
    steps:
      - run: echo ${{ needs.maven_package.outputs.app_version }}
      
  sonar:
    uses: ./.github/workflows/sonarcloud.yml
    permissions:
      pull-requests: read
    secrets: inherit
    needs: maven_package
